from sandbox.embed2learn.algos.npo_task_embedding import NPOTaskEmbedding
from sandbox.embed2learn.algos.ppo_task_embedding import PPOTaskEmbedding
from sandbox.embed2learn.algos.trpo_task_embedding import TRPOTaskEmbedding
